[package]
name = "pdf_merger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
lopdf = "0.34.0"
rfd = "0.15.0"
